# Generated by Django 3.2.4 on 2021-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('accounts', '0006_alter_profile_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(related_name='profiles', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='blog.SubCategory'),
        ),
    ]
