# Generated by Django 3.2.4 on 2021-06-17 01:17

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210612_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Bobur', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default="Yo'ldashev", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users/photos/'),
        ),
    ]
