# Generated by Django 3.2.4 on 2021-06-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210611_0632'),
        ('accounts', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='blog.Category'),
        ),
    ]
