# Generated by Django 3.2.4 on 2021-06-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210608_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent_cateogory',
            new_name='parent_category',
        ),
    ]
